# Generated by Django 4.0 on 2025-12-18 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_address'),
        ('users', '0002_useraddress'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Address',
        ),
    ]
