# Generated by Django 6.0 on 2025-12-28 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_userprofile_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraddress',
            name='mail',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
    ]
