# Generated by Django 4.0 on 2025-12-25 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_userprofile_is_verified'),
        ('products', '0003_delete_blog_model'),
        ('reviews', '0002_review_model_delete_review'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='review_model',
            unique_together={('product', 'user')},
        ),
    ]
