# Generated by Django 4.0 on 2025-12-15 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='customer_req',
            field=models.TextField(blank=True, help_text='Special instructions like extra sugar, more spice, etc.', null=True),
        ),
    ]
