# Generated by Django 4.0 on 2025-12-03 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='weight',
            field=models.CharField(choices=[('250', '250 gm'), ('500', '500 gm'), ('1000', '1 Kg')], default='500', max_length=10),
        ),
    ]
