# Generated by Django 4.0 on 2025-12-03 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('COD', 'Cash on Delivery'), ('PHONEPE', 'PhonePe'), ('GPAY', 'Google Pay'), ('UPI', 'UPI'), ('PAYTM', 'Paytm')], default='COD', max_length=20),
        ),
    ]
