# Generated by Django 4.0 on 2025-12-24 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_payment_status_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('COD', 'Cash on Delivery'), ('ONLINE', 'ONLINE'), ('PHONEPE', 'PhonePe'), ('GPAY', 'Google Pay'), ('UPI', 'UPI'), ('PAYTM', 'Paytm')], default='COD', max_length=20),
        ),
    ]
