# Generated by Django 6.0 on 2025-12-28 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_order_delivery_charge_order_subtotal'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='mail',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
    ]
