# Generated by Django 6.0 on 2025-12-29 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_order_mail'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='weight',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
