# Generated by Django 4.0 on 2025-11-21 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('telugu_name', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('category', models.CharField(choices=[('veg-pickles', 'non-veg-pickles'), ('sweets', 'podis'), ('savories', 'dry-fruits')], max_length=20)),
                ('image', models.ImageField(upload_to='products/')),
            ],
        ),
    ]
