# Generated by Django 4.0 on 2025-12-10 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(choices=[('pickles', 'pickles page'), ('sweets', 'sweets page'), ('savories', 'savories page'), ('masalas', 'masalas page'), ('dryfruits', 'dryfruits page'), ('home', 'home page')], max_length=50, unique=True)),
                ('images', models.ImageField(upload_to='banners/')),
                ('alt_text', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('telugu_name', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('category', models.CharField(choices=[('veg-pickles', 'Veg Pickles'), ('nonveg-pickles', 'Non-Veg Pickles'), ('sweets', 'Sweets'), ('podis', 'Podis'), ('savories', 'Savories'), ('dry-fruits', 'Dry Fruits')], max_length=20)),
                ('price_250', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('price_500', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('price_1000', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('image', models.ImageField(upload_to='products/')),
            ],
        ),
    ]
