# Generated by Django 4.0 on 2025-11-21 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.CharField(choices=[('veg-pickles', 'Veg Pickles'), ('non-veg-pickles', 'Non-Veg Pickles'), ('sweets', 'Sweets'), ('podis', 'Podis'), ('savories', 'Savories'), ('dry-fruits', 'Dry Fruits')], max_length=20),
        ),
    ]
