# Generated by Django 4.0 on 2025-12-18 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_blog_model'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blog_Model',
        ),
    ]
