# Generated by Django 4.0 on 2025-11-27 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_products_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(choices=[('pickles', 'pickles page'), ('sweets', 'sweets page'), ('savories', 'savories page'), ('masalas', 'masalas page'), ('dryfruits', 'dryfruits page'), ('home', 'home page')], max_length=50, unique=True)),
                ('images', models.ImageField(upload_to='banners/')),
                ('alt_text', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.CharField(choices=[('veg-pickles', 'Veg Pickles'), ('nonveg-pickles', 'Non-Veg Pickles'), ('sweets', 'Sweets'), ('podis', 'Podis'), ('savories', 'Savories'), ('dry-fruits', 'Dry Fruits')], max_length=20),
        ),
    ]
